### PR TITLE
Insert tweet, case, & vax counts to poller

### PR DESCRIPTION
**Pull request by ivanegam**
Added to `Pollers.TweetPoller` code to (1) first check if tweet, case, or vaccine count data for yesterday/day-before-yesterday is already in the database and, if not, (2) fetch an insert it.

### CODE REVIEW

**Review by mease — COMMENTED** [review]
I'm getting an error on "mix test".  It's trying to start up the poller, but there are no twitter creds. You can probably reproduce this if you delete your twitter secrets back to empty strings and run tests.  I think I have this fixed by following the steps here: https://virviil.github.io/2016/10/26/elixir-testing-without-starting-supervision-tree/

Let me know if I'm overlooking something.  Otherwise, are you okay if I push those updates directly to this branch?

**Review by mease — COMMENTED** [review]
Running pheonix server locally, tweet display looks great. When I go to graphs, it's logging an error to console and I'm not seeing any data displayed. Am I supposed to, or do we still have to hook this up to the graphs?

**Comment by ivanegam** [comment]
> I'm getting an error on "mix test". It's trying to start up the poller, but there are no twitter creds. You can probably reproduce this if you delete your twitter secrets back to empty strings and run tests. I think I have this fixed by following the steps here: https://virviil.github.io/2016/10/26/elixir-testing-without-starting-supervision-tree/
> 
> Let me know if I'm overlooking something. Otherwise, are you okay if I push those updates directly to this branch?

That's exactly the reason, yes. Yes, that would work and then we should be good to merge `Db_insert_counts`→`main`.

**Comment by mease** [comment]
> > I'm getting an error on "mix test". It's trying to start up the poller, but there are no twitter creds. You can probably reproduce this if you delete your twitter secrets back to empty strings and run tests. I think I have this fixed by following the steps here: https://virviil.github.io/2016/10/26/elixir-testing-without-starting-supervision-tree/
> > Let me know if I'm overlooking something. Otherwise, are you okay if I push those updates directly to this branch?
> 
> That's exactly the reason, yes. Yes, that would work and then we should be good to merge `Db_insert_counts`→`main`.

Pushed an update. Let me know if that doesn't work.

**Comment by ivanegam** [comment]
> > > I'm getting an error on "mix test". It's trying to start up the poller, but there are no twitter creds. You can probably reproduce this if you delete your twitter secrets back to empty strings and run tests. I think I have this fixed by following the steps here: https://virviil.github.io/2016/10/26/elixir-testing-without-starting-supervision-tree/
> > > Let me know if I'm overlooking something. Otherwise, are you okay if I push those updates directly to this branch?
> > 
> > 
> > That's exactly the reason, yes. Yes, that would work and then we should be good to merge `Db_insert_counts`→`main`.
> 
> Pushed an update. Let me know if that doesn't work.

Nice, all green on my end as well.

**Review by mease — APPROVED** [review]

**Pull request merged**
