### PR TITLE
Initial code for pulling tweets.

### PR DESCRIPTION
**Pull request by Alpoc**
Yeah this is real ugly but it work. Can refactor later if we really want.

### CODE REVIEW

**Comment by ivanegam** [comment]
Getting an `'Authorization Required'` error. Do I have to sign up w/ a Twitter dev account to get the `consumer_key` / `consumer_secret` / `access_token` / `access_token_secret`?

**Comment by Alpoc** [comment]
> 
> 
> Getting an `'Authorization Required'` error. Do I have to sign up w/ a Twitter dev account to get the `consumer_key` / `consumer_secret` / `access_token` / `access_token_secret`?

Yeah you would have to get a twitter dev account and create a project. . I didnt want to push my stuff to the git repo but where ever we deploy it i can add those in or sent it.

**Comment by Alpoc** [comment]
> nt

**Comment by ivanegam** [comment]
Works with my Twitter dev credentials. Since we're interested in daily historical tweets (as allowed by the 7-day limit), is `ExTwitter.stream_filter` what we need, or something like `ExTwitter.search`? Since `stream_filter` only shows the currently tweeted tweets...

**Comment by Alpoc** [comment]
> 
> 
> Works with my Twitter dev credentials. Since we're interested in daily historical tweets (as allowed by the 7-day limit), is `ExTwitter.stream_filter` what we need, or something like `ExTwitter.search`? Since `stream_filter` only shows the currently tweeted tweets...

@ivanegam, not sure. I just set it up assuming we would kick this of on a server constantly pulling tweets then manually get the top tweets for that day. We should discuss this during our next sprint planning.

**Pull request merged**
